config/routes.rb
Worddepot::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"

  resources :words

   root :to => 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, dependent: :destroy

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id
  belongs_to :word
  belongs_to :cart

end

app/models/word.rb
class Word < ActiveRecord::Base
  #http://railscasts.com/episodes/26-hackers-love-mass-assignment
  #todo understand mass assignments and hacking better
  attr_accessible :color, :meaning, :partofspeech, :points, :price, :sentence, :word

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  #ensure that there are no line items referencing this word
     def ensure_not_referenced_by_any_line_item
       if line_items.empty?
         return true
       else
         errors.add(:base, 'Line Items present')
         return false
       end
     end



  # All validations are to be grouped by field

  #word
  validates :word, presence: true, uniqueness: {:message => " already
exists."}


  #meaning
  validates :meaning, presence: true

  #part of speech
  validates :partofspeech, presence: true


  #sentence
  #validates :sentence

  #points
  #validates :points

  #price
  validates :price, numericality: {greater_than_or_equal_to: 0.01}


  #color
  validates :color,
            inclusion: {in: ['White', 'Blue', 'Green', 'Yellow'],
                        message: 'We are accepting only White, Blue ,
                                   Green, or Yellow at this time.'}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart= Cart.create
    session[:cart_id] = cart.id
    cart

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(params[:line_item])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @words=Word.order(:word)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Worddepot</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<div id="topMenu">
  <div id="circleContainer">
    <div class="circle"></div>
  </div>
  <div id="messageBar"> <%= @page_title || "Word Depot" %></div>
  <div id="squareContainer"></div>
</div>
<div id="mainContainer">

  <div id="leftMenu">
    <ul>
      <li><a href="http://www....">Home</a></li>
      <li><a href="http://www..../faq">Questions</a></li>
      <li><a href="http://www..../news">News</a></li>
      <li><a href="http://www..../contact">Contact</a></li>


    </ul>
  </div>

  <div id="main">
    <%= yield %>

  </div>

</div>
</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/store/index.html.erb
<% if notice %>
    <p id="notice"> <%= notice %>
<% end %>


<h1>Your Word Catalog</h1>

<!--Looping through all the reocrds from words instance variable-->
<% @words.each do |wordLoop| %>
    <div class="entry">
      <h3><%= wordLoop.word %></h3>
      <%= sanitize wordLoop.meaning %>
      <div class="price_line">
        <span class="price"><%= number_to_currency wordLoop.price %></span>
        <%=  button_to 'Add to Cart' , line_items_path(word_id: Word) %>
      </div>
    </div>

<% end %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
    <% if @word.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word
            from being saved:</h2>

          <ul>
            <% @word.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :word %>
      <br/>
      <%= f.text_field :word %>
    </div>

    <div class="field">
      <%= f.label :partofspeech %>
      <br/>
      <%= f.text_field :partofspeech %>
    </div>

    <div class="field">
      <%= f.label :meaning %>
      <br/>
      <%= f.text_area :meaning, rows: 4 %>
    </div>

    <div class="field">
      <%= f.label :sentence %>
      <br/>
      <%= f.text_area :sentence, rows: 3 %>
    </div>

    <div class="field">
      <%= f.label :points %>
      <br/>
      <%= f.text_field :points %>
    </div>
    <div class="field">
      <%= f.label :color %>
      <br/>
      <%= f.text_field :color %>
    </div>
    <div class="field">
      <%= f.label :price %>
      <br/>
      <%= f.text_field :price %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Listing words</h1>

<table>

  <% @words.each do |word| %>
      <tr class="<%= cycle 'list_line_even', 'list_line_odd' %>">

        <td><%= word.word %></td>
        <td><%= word.partofspeech %></td>

        <td class="list_sentence">
          <dl>
            <dt><%= word.meaning %></dt>
            <dd><%= word.sentence %></dd>
          </dl>
        </td>

        <td><%= word.points %></td>
        <td style="background-color: <%= word.color %>  ;"><%= word.color %></td>
        <td ><%= word.price %></td>

        <td class="list_actions">
          <%= link_to 'Show', word %>    <br/>
          <%= link_to 'Edit', edit_word_path(word) %>       <br/>
          <%= link_to 'Destroy', word, method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>


      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @word.word %>
</p>

<p>
  <b>Partofspeech:</b>
  <%= @word.partofspeech %>
</p>

<p>
  <b>Sentence:</b>
  <%= @word.sentence %>
</p>

<p>
  <b>Meaning:</b>
  <%= @word.meaning %>
</p>

<p>
  <b>Points:</b>
  <%= @word.points %>
</p>

<p>
  <b>Color:</b>
  <%= @word.color %>
</p>

<p>
  <b>Price:</b>
  <%= @word.price %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>